<template>
  <div class="app-container manual-schedule-page" :style="{ minHeight: 'calc(100vh - 100px)', height: pageHeight + 'px' }">
    <el-card shadow="never" class="header-card">
      <div slot="header" class="section-header">
        <div class="header-left"><span class="header-title">分切排程列表</span></div>
        <div class="header-right">
          <div class="search-input-group">
            <el-input v-model="slittingQuery.orderNo" size="small" clearable placeholder="按订单号搜索" style="width:150px" @keyup.enter.native="handleSlittingSearch" />
            <el-select v-model="slittingQuery.status" size="small" clearable placeholder="所有状态" style="width:130px;margin-left:5px" @change="handleSlittingSearch">
              <el-option label="所有状态" value="" />
              <el-option label="待分切（已排程未开工）" value="REWINDING_SCHEDULED" />
              <el-option label="进行中（已开工未完工）" value="IN_PROGRESS" />
              <el-option label="已完成" value="COMPLETED" />
              <el-option label="已终止" value="TERMINATED" />
            </el-select>
            <el-button-group style="margin-left:5px;">
              <el-button size="small" icon="el-icon-refresh-left" @click="resetSlittingSearch">重置</el-button>
              <el-button type="primary" size="small" icon="el-icon-search" @click="handleSlittingSearch">查询</el-button>
            </el-button-group>
          </div>
          <el-divider direction="vertical" />
          <el-button-group>
            <el-button type="success" size="small" icon="el-icon-plus" @click="openManualSlittingDialog">手动追加</el-button>
            <el-button type="primary" size="small" icon="el-icon-refresh" @click="loadSlittingSchedules">刷新列表</el-button>
          </el-button-group>
        </div>
      </div>
      <el-alert v-if="slittingLockSummary.unlockedRows > 0" type="warning" show-icon :closable="false" class="mb-10" :title="`锁料提醒：当前有 ${slittingLockSummary.unlockedRows} 条待分切订单存在未锁定面积，共 ${slittingLockSummary.unlockedArea} ㎡。建议先处理锁料风险。`" />
      <div class="table-main-area">
        <el-table ref="slittingTable" v-loading="slittingLoading" :data="slittingList" class="manual-schedule-table process-schedule-table" size="mini" border stripe style="width:100%" :max-height="tableHeight" :row-class-name="slittingRowClassName" @selection-change="handleSlittingPrintSelectionChange" @sort-change="handleSlittingSortChange">
          <el-table-column type="selection" width="40" align="center" />
          <el-table-column type="index" label="序号" width="52" align="center" />
          <el-table-column prop="schedule_id" label="排程号" width="102" align="center" sortable="custom" column-key="schedule_id">
            <template slot-scope="scope"><el-input-number v-if="scope.row.__editing && scope.row.__manual" v-model="scope.row.schedule_id" :min="1" :step="1" size="mini" controls-position="right" /><span v-else>{{ scope.row.schedule_id || '-' }}</span></template>
          </el-table-column>
          <el-table-column label="复卷时间" width="124" sortable="custom" column-key="rewinding_time">
            <template slot-scope="scope"><el-tag type="success" class="two-line-time-tag"><span class="two-line-time-text">{{ timeWindowLine(formatRewindingTimeWindow(scope.row), 0) }}</span><span class="two-line-time-text">{{ timeWindowLine(formatRewindingTimeWindow(scope.row), 1) }}</span></el-tag></template>
          </el-table-column>
          <el-table-column label="订单号" width="112" sortable="custom" column-key="order_no"><template slot-scope="scope"><el-button type="text" @click="handleOrderNoClick(scope.row)">{{ scope.row.order_no || '-' }}</el-button></template></el-table-column>
          <el-table-column label="交货日期" width="80" align="center" sortable="custom" column-key="delivery_date"><template slot-scope="scope"><span class="date-text">{{ scope.row.delivery_date | formatDate }}</span></template></el-table-column>
          <el-table-column prop="material_code" label="料号" width="230" class-name="wrap-col" show-overflow-tooltip sortable="custom" column-key="material_code">
            <template slot-scope="scope">
              <el-autocomplete v-if="scope.row.__editing && scope.row.__manual" v-model="scope.row.material_code" size="small" :fetch-suggestions="queryTapeSpecByMaterialCode" placeholder="请输入料号" :trigger-on-focus="false" @input="handleManualSlittingMaterialInput(scope.row, $event)" @select="handleManualSlittingMaterialSelect(scope.row, $event)">
                <template slot-scope="{ item }"><div style="display:flex;flex-direction:column;gap:2px;line-height:1.35;"><span style="font-weight:600;color:#303133;">{{ item.materialCode }}</span><span style="color:#909399;">{{ item.productName || '-' }}</span></div></template>
              </el-autocomplete>
              <span v-else>{{ scope.row.material_code || '-' }}</span>
            </template>
          </el-table-column>
          <el-table-column prop="material_name" label="产品名称" width="132" class-name="wrap-col" show-overflow-tooltip sortable="custom" column-key="material_name" />
          <el-table-column label="产品规格" width="132" align="right" sortable="custom" column-key="spec"><template slot-scope="scope">{{ formatOrderSpec(scope.row) }}</template></el-table-column>
          <el-table-column label="分切卷数" width="84" align="right" sortable="custom" column-key="schedule_qty"><template slot-scope="scope">{{ Number(scope.row.schedule_qty || 0) }}</template></el-table-column>
          <el-table-column label="已报工卷数" width="96" align="right" sortable="custom" column-key="slitting_report_qty"><template slot-scope="scope">{{ Number(scope.row.slitting_report_qty || 0).toFixed(2) }}</template></el-table-column>
          <el-table-column label="已报工面积(㎡)" width="120" align="right"><template slot-scope="scope">{{ formatArea(calcReportedAreaBySpec(scope.row, scope.row.slitting_report_qty)) }}</template></el-table-column>
          <el-table-column label="完成率" width="84" align="center" sortable="custom" column-key="slitting_completion_rate"><template slot-scope="scope">{{ formatProcessCompletionRate(scope.row.slitting_report_qty, scope.row.schedule_qty) }}</template></el-table-column>
          <el-table-column label="分切速度(卷/分)" width="118" align="center" sortable="custom" column-key="slitting_speed">
            <template slot-scope="scope"><el-input-number v-if="scope.row.__editing" v-model="scope.row.manual_slitting_speed" :min="0" :step="1" size="mini" controls-position="right" placeholder="可手输" @change="handleSlittingDateChange(scope.row)" /><span v-else>{{ formatSlittingSpeed(scope.row) }}</span></template>
          </el-table-column>
          <el-table-column label="计划时间" width="170" align="center" sortable="custom" column-key="packaging_date">
            <template slot-scope="scope"><el-date-picker v-if="scope.row.__editing" v-model="scope.row.packaging_date" type="date" size="small" format="yyyy-MM-dd" value-format="yyyy-MM-dd" @change="handleSlittingDateChange(scope.row)" /><span v-else>{{ formatDateOnly(scope.row.packaging_date) }}</span></template>
          </el-table-column>
          <el-table-column label="耗时" width="92" align="center" sortable="custom" column-key="slitting_duration"><template slot-scope="scope">{{ formatSlittingDuration(scope.row) }}</template></el-table-column>
          <el-table-column label="锁料提醒" width="108" align="center"><template slot-scope="scope"><el-tag v-if="getUnlockedArea(scope.row) > 0" type="warning">未锁{{ getUnlockedArea(scope.row).toFixed(0) }}㎡</el-tag><el-tag v-else type="success">已锁定</el-tag></template></el-table-column>
          <el-table-column label="机台号" width="124" align="center" sortable="custom" column-key="slitting_equipment">
            <template slot-scope="scope"><el-select v-if="scope.row.__editing" v-model="scope.row.slitting_equipment" size="small" placeholder="机台号" @change="handleSlittingEquipmentChange(scope.row)" @visible-change="handleSlittingEquipmentDropdownVisible(scope.row, $event)"><el-option v-for="eq in getSlittingEquipmentOptions(scope.row)" :key="eq.id" :label="slittingEquipmentOptionLabel(eq)" :value="eq.equipmentCode" :disabled="!!eq.unavailableReason" /></el-select><span v-else>{{ scope.row.slitting_equipment || '-' }}</span></template>
          </el-table-column>
          <el-table-column label="包装班组" width="140" align="center" sortable="custom" column-key="packaging_team">
            <template slot-scope="scope"><el-select v-if="scope.row.__editing" v-model="scope.row.packaging_team" size="small" clearable filterable placeholder="选择班组"><el-option v-for="team in packagingTeamList" :key="team.id" :label="team.teamName" :value="team.teamName" /></el-select><span v-else>{{ packagingTeamName(scope.row.packaging_team) }}</span></template>
          </el-table-column>
          <el-table-column label="状态" width="84" align="center" sortable="custom" column-key="status"><template slot-scope="scope"><el-tag :type="formatSlittingStatus(resolveSlittingDisplayStatus(scope.row)).type">{{ formatSlittingStatus(resolveSlittingDisplayStatus(scope.row)).label }}</el-tag></template></el-table-column>
          <el-table-column label="操作" width="132" align="center">
            <template slot-scope="scope"><div class="op-actions"><el-button class="op-main-btn" size="mini" :disabled="scope.row.__editing && !scope.row.packaging_date" @click="handleSlittingEditAction(scope.row)">{{ scope.row.__editing ? '确认' : '修改' }}</el-button><el-dropdown size="mini" trigger="click" @command="handleScheduleActionCommand"><el-button class="op-more-btn" size="mini">更多<i class="el-icon-arrow-down el-icon--right" /></el-button><el-dropdown-menu slot="dropdown"><el-dropdown-item :command="{ action: 'report', row: scope.row, processType: 'SLITTING' }">报工</el-dropdown-item><el-dropdown-item :command="{ action: 'reduce', row: scope.row }">减量</el-dropdown-item><el-dropdown-item :command="{ action: 'terminate', row: scope.row }" divided>终止</el-dropdown-item><el-dropdown-item v-if="scope.row.status === 'TERMINATED'" :command="{ action: 'resume', row: scope.row }">恢复</el-dropdown-item><el-dropdown-item :disabled="Number(scope.row.slitting_report_qty || 0) > 0" :command="{ action: 'reset', row: scope.row }" divided>回退到未排程</el-dropdown-item></el-dropdown-menu></el-dropdown></div></template>
          </el-table-column>
        </el-table>
      </div>
      <div class="pagination-container" style="text-align:right;">
        <el-pagination :current-page="slittingPage" :page-size="slittingPageSize" :page-sizes="pageSizes" layout="total, sizes, prev, pager, next, jumper" :total="slittingTotal" @size-change="handleSlittingSizeChange" @current-change="handleSlittingPageChange" />
      </div>
    </el-card>

    <!-- 手动分切对话框 -->
    <el-dialog title="手动添加分切排程（按订单选择）" :visible.sync="manualSlittingDialogVisible" width="920px" :close-on-click-modal="false" :append-to-body="false" custom-class="manual-slitting-dialog" @close="handleManualSlittingDialogClose">
      <el-form :inline="true" style="margin-bottom:10px;">
        <el-form-item label="订单号"><el-input v-model="manualSlittingQuery.orderNo" size="small" clearable placeholder="输入订单号搜索" style="width:220px" @input="handleManualSlittingQueryInput" @keyup.enter.native="loadManualSlittingCandidates" /></el-form-item>
        <el-form-item><el-button type="primary" size="small" icon="el-icon-search" @click="loadManualSlittingCandidates">查询</el-button></el-form-item>
        <el-form-item><el-button size="small" @click="selectAllManualSlittingCandidates">全选当前</el-button><el-button size="small" @click="clearManualSlittingSelection">清除选择</el-button></el-form-item>
      </el-form>
      <el-table ref="manualSlittingOrderTable" v-loading="manualSlittingLoading" :data="manualSlittingCandidates" :row-key="manualSlittingRowKey" class="manual-schedule-table" border stripe style="width:100%" max-height="320" @selection-change="handleManualSlittingSelectionChange" @row-click="handleManualSlittingRowClick">
        <el-table-column type="selection" :reserve-selection="true" width="48" align="center" />
        <el-table-column type="index" label="#" width="50" align="center" />
        <el-table-column label="客户代码" width="130" show-overflow-tooltip><template slot-scope="scope">{{ scope.row.customer_code || scope.row.customer || scope.row.customer_name || '-' }}</template></el-table-column>
        <el-table-column label="订单号" width="150" show-overflow-tooltip><template slot-scope="scope"><el-button type="text" @click.stop="handleOrderNoClick(scope.row)">{{ scope.row.order_no || '-' }}</el-button></template></el-table-column>
        <el-table-column prop="material_code" label="料号" width="220" show-overflow-tooltip />
        <el-table-column label="规格" width="190" show-overflow-tooltip><template slot-scope="scope">{{ formatOrderSpec(scope.row) }}</template></el-table-column>
        <el-table-column prop="remaining_qty" label="可排卷数" width="96" align="right" />
        <el-table-column label="本次排程卷数" width="150" align="center"><template slot-scope="scope"><div @click.stop><el-input-number v-model="scope.row._manual_qty" :min="1" :max="Math.max(1, isRpCustomer(scope.row) ? Number(scope.row.order_qty || scope.row.rolls || 0) : Number(scope.row.remaining_qty || 0))" :disabled="!scope.row._selected" size="mini" controls-position="right" /></div></template></el-table-column>
      </el-table>
      <div style="margin-top:10px;color:#606266;">已选明细：{{ manualSlittingSelectedRows.length }} 条</div>
      <div slot="footer"><el-button @click="manualSlittingDialogVisible = false">取消</el-button><el-button type="primary" :loading="manualSlittingSubmitting" @click="confirmManualSlittingSelection">确定</el-button></div>
    </el-dialog>

    <!-- 报工对话框 -->
    <el-dialog :title="workReportDialogTitle" :visible.sync="workReportDialogVisible" width="860px" @close="handleWorkReportDialogClose">
      <el-form :model="workReportForm" label-width="90px" inline>
        <el-form-item label="扫码明细"><el-input v-model="workReportScanCode" size="small" style="width:220px" @keyup.enter.native="applyWorkReportScan" /><el-button size="small" style="margin-left:6px" @click="applyWorkReportScan">匹配</el-button></el-form-item>
        <el-form-item label="开始时间"><el-date-picker v-model="workReportForm.startTime" type="datetime" size="small" format="yyyy-MM-dd HH:mm:ss" value-format="yyyy-MM-dd HH:mm:ss" /></el-form-item>
        <el-form-item label="结束时间"><el-date-picker v-model="workReportForm.endTime" type="datetime" size="small" format="yyyy-MM-dd HH:mm:ss" value-format="yyyy-MM-dd HH:mm:ss" /></el-form-item>
        <el-form-item label="生产数量"><el-input-number v-model="workReportForm.producedQty" :min="0.01" :step="1" :precision="2" size="small" controls-position="right" /></el-form-item>
        <el-form-item label="操作人"><el-input v-model="workReportForm.operator" size="small" style="width:140px" /></el-form-item>
        <el-form-item label="下工序"><el-switch v-model="workReportForm.proceedNextProcess" active-text="继续" inactive-text="不继续" /></el-form-item>
      </el-form>
      <el-form :model="workReportForm" label-width="90px"><el-form-item label="备注"><el-input v-model="workReportForm.remark" type="textarea" :rows="2" /></el-form-item></el-form>
      <div style="margin-bottom:8px;font-weight:600;">历史报工</div>
      <el-table v-loading="workReportLoading" :data="workReportList" border size="mini" max-height="280">
        <el-table-column type="index" label="#" width="50" align="center" />
        <el-table-column prop="start_time" label="开始时间" width="140"><template slot-scope="scope">{{ formatDateTime(scope.row.start_time) }}</template></el-table-column>
        <el-table-column prop="end_time" label="结束时间" width="140"><template slot-scope="scope">{{ formatDateTime(scope.row.end_time) }}</template></el-table-column>
        <el-table-column prop="produced_qty" label="生产数量" width="110" align="right" />
        <el-table-column prop="operator_name" label="操作人" width="120" />
        <el-table-column label="操作" width="120" align="center"><template slot-scope="scope"><el-button type="text" size="mini" @click="editWorkReportRow(scope.row)">修改</el-button><el-button type="text" size="mini" style="color:#F56C6C" @click="deleteWorkReportRow(scope.row)">删除</el-button></template></el-table-column>
        <el-table-column prop="created_at" label="录入时间" width="140"><template slot-scope="scope">{{ formatDateTime(scope.row.created_at) }}</template></el-table-column>
      </el-table>
      <div slot="footer"><el-button @click="workReportDialogVisible = false">取消</el-button><el-button type="primary" :loading="workReportSubmitting" @click="submitWorkReport">提交报工</el-button></div>
    </el-dialog>
  </div>
</template>

<script>
import manualScheduleMixin from './manualScheduleMixin'
import { getPendingOrders, getSlittingSchedules, getSlittingAvailability, updateSlittingSchedule, createSchedule, getLatestScheduleId } from '@/api/manualSchedule'
import { getSlittingProcessParamsList, getSlittingProcessParams } from '@/api/slittingProcessParams'
import uiConfig from '@/config/ui'

const SLITTING_SORT_STORAGE_KEY = 'manualSchedule:slittingSort:v1'

export default {
  name: 'SlittingScheduleProcess',
  mixins: [manualScheduleMixin],
  filters: {
    formatDate(val) {
      if (!val) return '-'
      const text = String(val).trim().replace(/\//g, '-')
      const datePart = text.length >= 10 ? text.substring(0, 10) : text
      const parts = datePart.split('-')
      if (parts.length >= 3) { return `${String(parts[1]).padStart(2, '0')}-${String(parts[2]).padStart(2, '0')}` }
      return datePart
    }
  },
  data() { return { slittingLoading: false, slittingList: [], slittingPage: 1, slittingPageSize: uiConfig.defaultPageSize, slittingTotal: 0, slittingQuery: { orderNo: '', status: 'REWINDING_SCHEDULED' }, slittingSort: { prop: null, order: null }, slittingSortSyncing: false, slittingLockSummary: { unlockedRows: 0, unlockedArea: 0 }, highlightSlittingDetailId: null, highlightSlittingTimer: null, slittingPrintSelections: [], manualSlittingDialogVisible: false, manualSlittingLoading: false, manualSlittingSubmitting: false, manualSlittingSearchTimer: null, manualSlittingCandidates: [], manualSlittingSelectedRows: [], manualSlittingQuery: { orderNo: '' } } },
  computed: { workReportRemainingQtyHint() { const planned = Number(this.workReportPlannedQty || 0); if (!(planned > 0)) return -1; const reported = this.sumWorkReportProducedQty(this.workReportList); return Number(Math.max(planned - reported, 0).toFixed(2)) } },
  mounted() { this.lockOuterScroll(); this.updateTableMaxHeight(); window.addEventListener('resize', this.updateTableMaxHeight); this.restoreSlittingSortState(); this.loadSlittingSchedules(); this.loadEquipmentList(); this.loadEquipmentScheduleConfigMap(); this.loadCoatingTeamList(); window.addEventListener('schedule:jumpToSlitting', this.onExternalJumpToSlitting) },
  beforeDestroy() { this.unlockOuterScroll(); window.removeEventListener('resize', this.updateTableMaxHeight); if (this.highlightSlittingTimer) { clearTimeout(this.highlightSlittingTimer); this.highlightSlittingTimer = null }; if (this.manualSlittingSearchTimer) { clearTimeout(this.manualSlittingSearchTimer); this.manualSlittingSearchTimer = null }; window.removeEventListener('schedule:jumpToSlitting', this.onExternalJumpToSlitting) },
  methods: {
    syncActiveTableLayout() { this.doTableLayout('slittingTable') },
    resolveSlittingDisplayStatus(row) { const raw = String((row && row.status) || '').toUpperCase(); return raw || 'REWINDING_SCHEDULED' },
    triggerWorkReportRefresh() { this.loadWorkReportList(); this.loadSlittingSchedules() },
    handleManualSlittingMaterialInput(row, value) { this.handleManualMaterialInput(row, value) },
    handleManualSlittingMaterialSelect(row, item) { this.handleManualMaterialSelect(row, item, 'slitting') },
    formatSlittingSpeed(row) { const speed = this.resolveSlittingSpeed(row); if (speed <= 0) return '-'; return Number.isInteger(speed) ? String(speed) : speed.toFixed(1) },
    formatSlittingDuration(row) { const qty = Number(row.schedule_qty || 0); const speed = this.resolveSlittingSpeed(row); if (qty <= 0 || speed <= 0) { const m = Number(row.slitting_duration_minutes || row.slittingDurationMinutes || 0); if (m <= 0) return '-'; return `${Math.floor(m/60)}小时${m%60}分钟` }; const rm = Math.ceil(qty / speed); return `${Math.floor(rm/60)}小时${rm%60}分钟` },
    formatRewindingTimeWindow(row) { if (!row) return '-'; const start = row.rewinding_start_time || row.rewindingStartTime || row.rewinding_date || row.rewindingDate; const end = row.rewinding_end_time || row.rewindingEndTime; const sd = this.parseDateTimeValue(start); const ed = this.parseDateTimeValue(end); if (sd && ed) return this.formatTimeWindow(sd, ed); if (sd) { const m = this.calcRewindingMinutes(row); if (m > 0) return this.formatTimeWindow(sd, new Date(sd.getTime() + m * 60000)) }; return start ? this.formatDateTime(start) : '-' },
    slittingEquipmentOptionLabel(eq) { const base = `${(eq && eq.equipmentCode) || ''}${eq && eq.equipmentName ? '-' + eq.equipmentName : ''}`; if (eq && eq.unavailableReason) return `${base}（不可用: ${eq.unavailableReason}）`; if (!eq || !eq.suggestedStart) return base; return `${base}（最早:${this.formatDateTime(eq.suggestedStart)}）` },
    getSlittingEquipmentOptions(row) { const key = `${'SLITTING'}@@${row ? (row.id || row.schedule_id || Math.random()) : Math.random()}`; const cached = this.slittingEquipmentOptionsMap[key]; return (Array.isArray(cached) && cached.length) ? cached : (this.slittingEquipmentList || []) },
    refreshSlittingLockSummary() { const rows = this.slittingList || []; let uR = 0, uA = 0; rows.forEach(r => { const ua = this.getUnlockedArea(r); if (ua > 0) { uR += 1; uA += ua } }); this.slittingLockSummary = { unlockedRows: uR, unlockedArea: Number(uA.toFixed(2)) } },
    slittingRowClassName({ row }) { if (Number(this.highlightSlittingDetailId || 0) > 0 && Number((row && row.order_detail_id) || 0) === Number(this.highlightSlittingDetailId)) return 'slitting-highlight-row'; return '' },
    handleSlittingEquipmentChange(row) { this.updateSlittingAvailability(row) },
    handleSlittingDateChange(row) { this.updateSlittingAvailability(row) },
    handleSlittingEditAction(row) { if (!row.__editing) { this.$set(row, '__editing', true); this.refreshSlittingEquipmentOptions(row); return }; this.handleUpdateSlittingSchedule(row) },
    resolveSlittingDimensions(row) { return { totalThickness: Number(row.total_thickness || row.thickness || 0), processLength: Number(row.process_length || row.processLength || row.length || 0), processWidth: Number(row.process_width || row.processWidth || row.width || 0), equipmentCode: this.normalizeEquipmentCode(row.equipment_code || row.equipmentCode || row.slitting_equipment || row.slittingEquipment) } },
    normalizeDimensionValue(value) { const num = Number(value); if (!Number.isFinite(num) || num <= 0) return ''; return Number.isInteger(num) ? String(num) : String(Number(num.toFixed(4))) },
    makeSlittingDimensionKey(totalThickness, processLength, processWidth, equipmentCode) { const t = this.normalizeDimensionValue(totalThickness); const l = this.normalizeDimensionValue(processLength); const w = this.normalizeDimensionValue(processWidth); if (!t || !l || !w) return ''; return `${t}|${l}|${w}@@${this.normalizeEquipmentCode(equipmentCode)}` },
    resolveSlittingSpeed(row) { const manual = Number(row.manual_slitting_speed || row.manualSlittingSpeed || 0); if (manual > 0) return manual; const direct = Number(row.slitting_speed || row.slittingSpeed || 0); if (direct > 0) return direct; const { totalThickness, processLength, processWidth, equipmentCode } = this.resolveSlittingDimensions(row); const ek = this.makeSlittingDimensionKey(totalThickness, processLength, processWidth, equipmentCode); const exact = Number(this.slittingSpeedMap[ek] || 0); if (exact > 0) return exact; return Number(this.slittingSpeedMap[this.makeSlittingDimensionKey(totalThickness, processLength, processWidth)] || 0) },
    async loadSlittingSpeedMap() { try { const res = await getSlittingProcessParamsList({ current: 1, page: 1, size: 5000 }); const list = res.data?.list || res.data?.records || []; const speedMap = {}; list.forEach(item => { const totalThickness = item.totalThickness != null ? item.totalThickness : item.total_thickness; const processLength = item.processLength != null ? item.processLength : item.process_length; const processWidth = item.processWidth != null ? item.processWidth : item.process_width; const equipmentCode = this.normalizeEquipmentCode(item.equipmentCode || item.equipment_code); const speed = Number(item.productionSpeed || item.production_speed || item.slittingSpeed || item.slitting_speed || 0); const dimKey = this.makeSlittingDimensionKey(totalThickness, processLength, processWidth, equipmentCode); if (dimKey && speed > 0) { speedMap[dimKey] = speed; if (!equipmentCode) { speedMap[this.makeSlittingDimensionKey(totalThickness, processLength, processWidth)] = speed } } }); this.slittingSpeedMap = speedMap } catch (error) { console.error('加载分切工艺参数失败', error) } },
    async ensureSlittingSpeedForRows(rows) { const list = Array.isArray(rows) ? rows : []; if (!list.length) return; const tasks = list.map(async row => { const { totalThickness, processLength, processWidth, equipmentCode } = this.resolveSlittingDimensions(row); const exactKey = this.makeSlittingDimensionKey(totalThickness, processLength, processWidth, equipmentCode); const commonKey = this.makeSlittingDimensionKey(totalThickness, processLength, processWidth); if (!commonKey) return; if (Number(this.slittingSpeedMap[exactKey] || 0) > 0 || Number(this.slittingSpeedMap[commonKey] || 0) > 0) return; try { let speed = 0; if (equipmentCode) { const exactRes = await getSlittingProcessParams(totalThickness, processLength, processWidth, equipmentCode); speed = Number((exactRes.data || {}).productionSpeed || (exactRes.data || {}).production_speed || (exactRes.data || {}).slittingSpeed || (exactRes.data || {}).slitting_speed || 0); if (speed > 0) this.$set(this.slittingSpeedMap, exactKey, speed) }; if (speed <= 0) { const commonRes = await getSlittingProcessParams(totalThickness, processLength, processWidth); speed = Number((commonRes.data || {}).productionSpeed || (commonRes.data || {}).production_speed || (commonRes.data || {}).slittingSpeed || (commonRes.data || {}).slitting_speed || 0) }; if (speed > 0) { this.$set(this.slittingSpeedMap, commonKey, speed); if (equipmentCode) this.$set(this.slittingSpeedMap, exactKey, speed) } } catch (e) { /* ignore */ } }); await Promise.all(tasks) },
    async updateSlittingAvailability(row) { try { if (!row || !row.schedule_id || !row.slitting_equipment) return; if (!row.packaging_date) return; const res = await getSlittingAvailability({ scheduleId: row.schedule_id, slittingEquipment: row.slitting_equipment, packagingDate: row.packaging_date, manualSlittingSpeed: Number(row.manual_slitting_speed || 0) > 0 ? Number(row.manual_slitting_speed) : null, looseDurationMode: true }); if (res.code === 200 || res.code === 20000) { const data = res.data || {}; if (data.suggestedStart) this.$set(row, 'packaging_date', data.suggestedStart); if (data.warning) this.$message.warning(data.warning) } } catch (e) { this.$message.warning(this.parseApiError(e, '未能获取分切机台空闲时间')) } },
    async refreshSlittingEquipmentOptions(row) { if (!row || !row.schedule_id) return; if (!row.packaging_date) { this.$set(this.rewindingEquipmentOptionsMap, `${'SLITTING'}@@${row ? (row.id || row.schedule_id || Math.random()) : Math.random()}`, this.slittingEquipmentList || []); return }; const optionKey = `${'SLITTING'}@@${row ? (row.id || row.schedule_id || Math.random()) : Math.random()}`; const loadingKey = `SLITTING@${optionKey}`; if (this.equipmentOptionLoadingMap[loadingKey]) return; this.$set(this.equipmentOptionLoadingMap, loadingKey, true); try { const tasks = (this.slittingEquipmentList || []).map(async eq => { const ec = eq && eq.equipmentCode; if (!ec) return null; try { const res = await getSlittingAvailability({ scheduleId: row.schedule_id, slittingEquipment: ec, packagingDate: row.packaging_date, manualSlittingSpeed: Number(row.manual_slitting_speed || 0) > 0 ? Number(row.manual_slitting_speed) : null, looseDurationMode: true }); if (!(res.code === 200 || res.code === 20000)) return null; const data = res.data || {}; if (!data.suggestedStart) return { ...eq, unavailableReason: '机台暂无可排时间', _sortTs: Number.MAX_SAFE_INTEGER, _available: false }; return { ...eq, suggestedStart: data.suggestedStart, _sortTs: this.toDateObj(data.suggestedStart) ? this.toDateObj(data.suggestedStart).getTime() : Number.MAX_SAFE_INTEGER, _available: true } } catch (e) { return { ...eq, unavailableReason: this.parseApiError(e, '未维护机台能力参数'), _sortTs: Number.MAX_SAFE_INTEGER, _available: false } } }); const resolved = (await Promise.all(tasks)).filter(Boolean); resolved.sort((a, b) => { const av = Number(!!a._available); const bv = Number(!!b._available); if (av !== bv) return bv - av; const t = Number(a._sortTs || Number.MAX_SAFE_INTEGER) - Number(b._sortTs || Number.MAX_SAFE_INTEGER); if (t !== 0) return t; return String(a.equipmentCode || '').localeCompare(String(b.equipmentCode || '')) }); if (resolved.length) this.$set(this.slittingEquipmentOptionsMap, optionKey, resolved); else this.$set(this.slittingEquipmentOptionsMap, optionKey, this.slittingEquipmentList || []) } finally { this.$set(this.equipmentOptionLoadingMap, loadingKey, false) } },
    handleSlittingEquipmentDropdownVisible(row, visible) { if (visible) this.refreshSlittingEquipmentOptions(row) },
    restoreSlittingSortState() { try { const raw = window.localStorage.getItem(SLITTING_SORT_STORAGE_KEY); if (!raw) return; const parsed = JSON.parse(raw); const prop = String((parsed && parsed.prop) || '').trim(); const order = parsed && parsed.order; if (!prop || !['ascending', 'descending'].includes(order)) return; this.slittingSort = { prop, order } } catch (e) { /* ignore */ } },
    persistSlittingSortState() { try { const { prop, order } = this.slittingSort || {}; if (!prop || !order) { window.localStorage.removeItem(SLITTING_SORT_STORAGE_KEY); return }; window.localStorage.setItem(SLITTING_SORT_STORAGE_KEY, JSON.stringify({ prop, order })) } catch (e) { /* ignore */ } },
    syncSlittingTableSortIndicator() { this.$nextTick(() => { const table = this.$refs.slittingTable; if (!table) return; const { prop, order } = this.slittingSort || {}; if (!prop || !order) { if (typeof table.clearSort === 'function') table.clearSort(); return }; if (typeof table.sort === 'function') { this.slittingSortSyncing = true; table.sort(prop, order); this.$nextTick(() => { this.slittingSortSyncing = false }) } }) },
    async loadSlittingSchedules() { this.slittingLoading = true; try { if (!Object.keys(this.rewindingSpeedMap).length) await this.loadRewindingSpeedMapAsync(); if (!Object.keys(this.slittingSpeedMap).length) await this.loadSlittingSpeedMap(); const res = await getSlittingSchedules({ current: this.slittingPage, size: this.slittingPageSize, orderNo: (this.slittingQuery.orderNo || '').trim(), status: this.slittingQuery.status || null, sortProp: (this.slittingSort && this.slittingSort.prop) || null, sortOrder: (this.slittingSort && this.slittingSort.order) || null }); if (res.code === 200 || res.code === 20000) { const pageData = res.data || {}; const records = pageData.records || pageData.list || []; const mappedSlitting = records.map(item => { const statusText = String(item.status || '').trim().toUpperCase(); const hasPlan = this.hasSlittingPlan(item); const planTimeRaw = item.slitting_start_time || item.rewinding_end_time || item.packaging_date || item.slitting_schedule_date || ''; let planTime = planTimeRaw; if (planTime && String(planTime).length === 10) planTime = `${planTime} 08:00:00`; let finalStatus = statusText; if (!statusText || statusText === 'REWINDING_SCHEDULED') finalStatus = hasPlan ? 'SLITTING_SCHEDULED' : 'REWINDING_SCHEDULED'; return { ...item, status: finalStatus, packaging_date: planTime, slitting_equipment: item.slitting_equipment || '', __editing: !hasPlan && statusText !== 'TERMINATED', __manual: false } }); this.slittingList = await this.enrichMaterialNamesFromSpec(mappedSlitting); this.refreshSlittingLockSummary(); const backendSortFields = ['schedule_id', 'order_no', 'packaging_date', 'delivery_date']; if (!this.slittingSort || !backendSortFields.includes(this.slittingSort.prop)) this.applySlittingSort(); await this.ensureRewindingSpeedForRowsAsync(this.slittingList); await this.ensureSlittingSpeedForRows(this.slittingList); this.slittingTotal = Number(pageData.total || 0) } else { this.slittingList = []; this.slittingLockSummary = { unlockedRows: 0, unlockedArea: 0 }; this.slittingTotal = 0 } } catch (error) { this.$message.error('加载分切已排失败'); this.slittingLockSummary = { unlockedRows: 0, unlockedArea: 0 } } finally { this.slittingLoading = false; this.relayoutTable('slittingTable'); this.syncSlittingTableSortIndicator() } },
    async loadRewindingSpeedMapAsync() { try { const { getRewindingProcessParamsList } = await import('@/api/rewindingProcessParams'); const res = await getRewindingProcessParamsList({ current: 1, page: 1, size: 5000 }); const list = res.data?.list || res.data?.records || []; const speedMap = {}; list.forEach(item => { const materialCode = this.normalizeMaterialCode(item.materialCode || item.material_code); const equipmentCode = this.normalizeEquipmentCode(item.equipmentCode || item.equipment_code); const speed = Number(item.rewindingSpeed || item.rewinding_speed || 0); if (materialCode && speed > 0) { speedMap[this.makeSpeedKey(materialCode, equipmentCode)] = speed; if (!equipmentCode) speedMap[materialCode] = speed } }); this.rewindingSpeedMap = speedMap } catch (error) { console.error('加载复卷工艺参数失败', error) } },
    async ensureRewindingSpeedForRowsAsync(rows) { const list = Array.isArray(rows) ? rows : []; const missingPairs = [...new Set(list.map(r => { const code = this.normalizeMaterialCode(r.material_code || r.materialCode); const equipmentCode = this.resolveRewindingEquipmentCode(r); return this.makeSpeedKey(code, equipmentCode) }).filter(key => key && !this.rewindingSpeedMap[key]))]; if (!missingPairs.length) return; const { getRewindingProcessParams } = await import('@/api/rewindingProcessParams'); const tasks = missingPairs.map(async key => { try { const [code, equipmentCode = ''] = String(key || '').split('@@'); if (!code) return; let speed = 0; const res = await getRewindingProcessParams(code, equipmentCode); speed = Number((res.data || {}).rewindingSpeed || (res.data || {}).rewinding_speed || 0); if (speed <= 0) { const baseCode = this.toBaseMaterialCode(code); if (baseCode && baseCode !== code) { const baseRes = await getRewindingProcessParams(baseCode, equipmentCode); speed = Number((baseRes.data || {}).rewindingSpeed || (baseRes.data || {}).rewinding_speed || 0); if (speed > 0) { this.$set(this.rewindingSpeedMap, this.makeSpeedKey(baseCode, equipmentCode), speed); this.$set(this.rewindingSpeedMap, baseCode, speed) } } }; if (speed > 0) { this.$set(this.rewindingSpeedMap, this.makeSpeedKey(code, equipmentCode), speed); if (!equipmentCode) this.$set(this.rewindingSpeedMap, code, speed) } } catch (e) { /* ignore */ } }); await Promise.all(tasks) },
    hasSlittingPlan(row) { if (!row) return false; const equipment = String(row.slitting_equipment || row.rewinding_equipment || '').trim(); if (!equipment) return false; return !!this.parseDateTimeValue(row.slitting_start_time || row.packaging_date || row.slitting_schedule_date || '') },
    handleSlittingSizeChange(size) { this.slittingPageSize = size; this.slittingPage = 1; this.loadSlittingSchedules() },
    handleSlittingPageChange(page) { this.slittingPage = page; this.loadSlittingSchedules() },
    handleSlittingSearch() { this.slittingPage = 1; this.loadSlittingSchedules() },
    resetSlittingSearch() { this.slittingQuery.orderNo = ''; this.slittingQuery.status = 'REWINDING_SCHEDULED'; this.slittingPage = 1; this.loadSlittingSchedules() },
    handleSlittingPrintSelectionChange(selection) { this.slittingPrintSelections = Array.isArray(selection) ? selection : [] },
    getSlittingSortValue(row, key) { const nv=v=>Number(v||0); const sv=v=>String(v==null?'':v).toUpperCase(); if (!row) return ''; if (key==='schedule_id') return nv(row.schedule_id||row.id); if (key==='spec'){const t=nv(row.thickness),w=nv(row.width),l=nv(row.length);return t*1e8+w*1e4+l}; if (key==='schedule_qty')return nv(row.schedule_qty); if (key==='slitting_report_qty')return nv(row.slitting_report_qty); if (key==='slitting_completion_rate')return nv(this.formatProcessCompletionRate(row.slitting_report_qty,row.schedule_qty).replace('%','')); if (key==='slitting_speed')return nv(this.resolveSlittingSpeed(row)); if (key==='slitting_duration')return nv(this.calcSlittingMinutes(row)); if (key==='packaging_date')return this.toDateValue(row.packaging_date||row.slitting_start_time); if (key==='rewinding_time')return this.toDateValue(row.rewinding_end_time||row.rewinding_end_date||row.rewinding_date); return sv(row[key]) },
    toDateValue(value) { if (!value) return 0; const d = new Date(String(value).replace(' ', 'T')); return Number.isNaN(d.getTime()) ? 0 : d.getTime() },
    calcSlittingMinutes(row) { const qty = Number(row.schedule_qty || 0); const speed = this.resolveSlittingSpeed(row); if (qty > 0 && speed > 0) return Math.ceil(qty / speed); return Number(row.slitting_duration_minutes || row.slittingDurationMinutes || 0) },
    applySlittingSort() { const src = Array.isArray(this.slittingList) ? [...this.slittingList] : []; const { prop, order } = this.slittingSort || {}; if (!prop || !order) { this.slittingList = src; return }; const factor = order === 'ascending' ? 1 : -1; src.sort((a, b) => { const av = this.getSlittingSortValue(a, prop); const bv = this.getSlittingSortValue(b, prop); if (av === bv) return 0; return av > bv ? factor : -factor }); this.slittingList = src },
    handleSlittingSortChange({ prop, order, column }) { if (this.slittingSortSyncing) return; const key = (column && column.columnKey) || prop; this.slittingSort = { prop: key, order: order || null }; this.persistSlittingSortState(); const backendSortFields = ['schedule_id', 'order_no', 'packaging_date', 'delivery_date']; if (!key || backendSortFields.includes(key)) { this.loadSlittingSchedules(); return }; this.applySlittingSort() },
    onExternalJumpToSlitting(e) { const { orderDetailId } = e.detail || {}; if (orderDetailId) { this.slittingPage = 1; this.loadSlittingSchedules().then(() => { this.highlightSlittingDetailId = Number(orderDetailId); if (this.highlightSlittingTimer) clearTimeout(this.highlightSlittingTimer); this.highlightSlittingTimer = setTimeout(() => { this.highlightSlittingDetailId = null }, 10000) }) } },
    isRpCustomer(item) {
      if (!item) return false
      const customer = String(item.customer || item.customer_name || '').toUpperCase().trim()
      const rpCodes = ['RP01', 'GDRP01', 'JSRP01', 'JXRP001', 'LZRP01', 'SHRP001']
      return rpCodes.some(code => customer === code || customer.startsWith(code))
    },
    isManualSlittingCandidate(item) {
      if (!item) return false
      const isRp = this.isRpCustomer(item)
      const remainingQty = Number(item.remaining_qty || 0)
      if (!(remainingQty > 0) && !isRp) return false
      const status = String(item.schedule_status || item.status || '').toUpperCase()
      if (['COMPLETED', 'CANCELLED', 'CANCELED', 'TERMINATED'].includes(status) && !isRp) return false
      if (String(item.schedule_type || '').toUpperCase() === 'SLITTING_MANUAL') return false
      return true
    },
    async openManualSlittingDialog() { this.manualSlittingDialogVisible = true; this.manualSlittingSelectedRows = []; await this.loadManualSlittingCandidates() },
    handleManualSlittingDialogClose() { if (this.manualSlittingSearchTimer) { clearTimeout(this.manualSlittingSearchTimer); this.manualSlittingSearchTimer = null } },
    handleManualSlittingQueryInput() { if (this.manualSlittingSearchTimer) clearTimeout(this.manualSlittingSearchTimer); const keyword = String(this.manualSlittingQuery.orderNo || '').trim(); if (keyword && keyword.length < 3) return; this.manualSlittingSearchTimer = setTimeout(() => { this.loadManualSlittingCandidates(false) }, 350) },
    async loadManualSlittingCandidates(force = true) { const keyword = String(this.manualSlittingQuery.orderNo || '').trim(); if (!force && keyword && keyword.length < 3) return; this.manualSlittingLoading = true; try { const res = await getPendingOrders({ current: 1, size: 50, includeCompleted: true, orderNo: keyword }); if (!(res.code === 200 || res.code === 20000)) { this.manualSlittingCandidates = []; this.manualSlittingSelectedRows = []; return }; const records = (res.data || {}).records || (res.data || {}).list || []; this.manualSlittingCandidates = records.filter(item => this.isManualSlittingCandidate(item)).map(item => { const isRp = this.isRpCustomer(item); const orderQty = Number(item.order_qty || item.rolls || 0); const maxQty = isRp ? Math.max(1, orderQty) : Math.max(1, Math.floor(Number(item.remaining_qty || 0))); return { ...item, _selected: false, _manual_qty: maxQty } }); this.manualSlittingSelectedRows = [] } catch (e) { this.manualSlittingCandidates = []; this.manualSlittingSelectedRows = [] } finally { this.manualSlittingLoading = false } },
    handleManualSlittingSelectionChange(selection) { this.manualSlittingSelectedRows = selection || []; const ss = new Set((selection || []).map(item => Number(item.order_detail_id || 0))); (this.manualSlittingCandidates || []).forEach(item => { const picked = ss.has(Number(item.order_detail_id || 0)); this.$set(item, '_selected', picked); if (picked) { const isRp = this.isRpCustomer(item); const orderQty = Number(item.order_qty || item.rolls || 0); const maxQty = isRp ? Math.max(1, orderQty) : Math.max(1, Math.floor(Number(item.remaining_qty || 0))); if (!(Number(item._manual_qty || 0) > 0) || Number(item._manual_qty) > maxQty) this.$set(item, '_manual_qty', maxQty) } }) },
    manualSlittingRowKey(row) { const id = Number((row && (row.order_detail_id || row.id)) || 0); if (id > 0) return `OD-${id}`; return `TMP-${String((row && row.order_no) || '')}-${String((row && row.material_code) || '')}` },
    handleManualSlittingRowClick(row, column, event) { const table = this.$refs.manualSlittingOrderTable; if (!table || !row) return; const target = event && event.target; if (target && (target.closest('.el-input-number') || target.closest('.el-input') || target.closest('.el-checkbox') || target.closest('.el-button') || target.closest('.el-button--text') || target.closest('.el-select') || target.closest('.el-date-editor'))) return; table.toggleRowSelection(row, !row._selected) },
    selectAllManualSlittingCandidates() { const table = this.$refs.manualSlittingOrderTable; if (!table) return; table.clearSelection(); (this.manualSlittingCandidates || []).forEach(r => table.toggleRowSelection(r, true)) },
    clearManualSlittingSelection() { const table = this.$refs.manualSlittingOrderTable; if (!table) return; table.clearSelection() },
    async confirmManualSlittingSelection() { const selected = this.manualSlittingSelectedRows || []; if (!selected.length) { this.$message.warning('请至少选择一条订单明细'); return }; this.manualSlittingSubmitting = true; try { let failCount = 0; const createdRows = []; for (const row of selected) { try { if (!row || !row.order_detail_id) { failCount++; continue }; const isRp = this.isRpCustomer(row); const orderQty = Number(row.order_qty || row.rolls || 0); const maxQty = isRp ? Math.max(1, orderQty) : Math.floor(Number(row.remaining_qty || 0)); const pickQty = Math.floor(Number(row._manual_qty || 0)); if (!(pickQty > 0) || pickQty > maxQty) { failCount++; continue }; try { if (!isRp) { const lr = await getLatestScheduleId({ orderDetailId: row.order_detail_id }); if (lr && (lr.code === 200 || lr.code === 20000) && Number(lr.data || 0) > 0) { failCount++; continue } } } catch (e) { /* ignore */ }; const cr = await createSchedule({ orderNo: row.order_no, orderDetailId: row.order_detail_id, materialCode: row.material_code, materialName: row.material_name, width: row.width, length: row.length, thickness: row.thickness, orderQty: row.order_qty, scheduleQty: pickQty, scheduleType: 'SLITTING_MANUAL', status: 'PENDING', remark: '手动分切排程' }); if (!(cr.code === 200 || cr.code === 20000)) throw new Error(cr.message || '创建排程失败'); const sid = Number(cr.data || 0); if (!(sid > 0)) throw new Error('未返回排程ID'); createdRows.push({ schedule_id: sid, order_detail_id: row.order_detail_id, status: 'REWINDING_SCHEDULED', order_no: row.order_no, customer_name: row.customer_name, material_code: row.material_code, material_name: row.material_name, width: row.width, length: row.length, thickness: row.thickness, schedule_qty: pickQty, packaging_date: '', slitting_equipment: '', packaging_team: '', rewinding_equipment: '', manual_slitting_speed: 0, __editing: true, __manual: true }) } catch (err) { failCount++ } }; if (createdRows.length) { this.slittingPage = 1; await this.loadSlittingSchedules() }; this.manualSlittingDialogVisible = false; this.$message.success(`已创建 ${createdRows.length} 条${failCount > 0 ? `，失败 ${failCount} 条` : ''}`) } catch (e) { this.$message.error((e && e.message) || '创建失败') } finally { this.manualSlittingSubmitting = false } },
    async handleUpdateSlittingSchedule(row) { if (!row.schedule_id || Number(row.schedule_id) <= 0) { this.$message.warning('手动添加行请先填写有效排程号'); return }; if (!String(row.material_code || '').trim()) { this.$message.warning('请先填写料号'); return }; if (!row.packaging_date) { this.$message.warning('请选择分切计划日期'); return }; const rewindingEnd = this.parseDateTimeValue(row.rewinding_end_time || row.rewindingEndTime); const selectedStart = this.parseDateTimeValue(row.packaging_date); if (rewindingEnd && selectedStart && selectedStart.getTime() < rewindingEnd.getTime()) { const adjusted = this.toDateTimeString(rewindingEnd); this.$set(row, 'packaging_date', adjusted); this.$message.warning(`分切开始已自动调整为：${this.formatDateTime(adjusted)}`) }; try { await this.ensureRowMaterialNameBySpec(row); const res = await updateSlittingSchedule({ scheduleId: row.schedule_id, packagingDate: row.packaging_date, slittingEquipment: row.slitting_equipment || row.rewinding_equipment, packagingTeam: row.packaging_team, manualSlittingSpeed: Number(row.manual_slitting_speed || 0) > 0 ? Number(row.manual_slitting_speed) : null, looseDurationMode: true }); if (res.code === 200 || res.code === 20000) { this.$message.success('分切排程修改成功'); this.$set(row, '__editing', false); this.$set(row, 'status', 'CONFIRMED'); this.loadSlittingSchedules() } else this.$message.error(res.message || '修改失败') } catch (err) { this.$message.error('修改失败: ' + (err.message || '未知错误')) } }
  }
}
</script>

<style scoped>
@import './manualScheduleShared.scss';
</style>

<style>
.manual-slitting-dialog .el-dialog__body {
  overflow-x: auto;
}
</style>
